### PR TITLE
[pull request created by mistake]

### PR DESCRIPTION
**Pull request by Necktschnagge**

### CODE REVIEW

**Comment by xditya** [comment]
It makes no sense, why must you remove the variables part to add your data in a public repository?

**Comment by Necktschnagge** [comment]
I am sorry, I wanted to make a Pull request inside my own repository.
Hit the wrong button.

**Comment by Necktschnagge** [comment]
I there any way to entirely delete this pull request?

**Comment by xditya** [comment]
@Necktschnagge "Close pr", nothing else.

**Pull request closed without merging**
